version: '3.9'
services:
  devices-simulation:
    build: 
      context: .
      # Choose 'development' for build with dev and test dependencies
      # Choose 'test' for build that runs unit and coverage tests automatically
      # Remove this target or set to 'production' for build with production dependencies
      target: development
    env_file:
      - .env
    image: devices-simulation:latest
    environment:
      - TZ=America/Sao_Paulo
      - ENVIRONMENT=dev
    # networks:
    #   - devices-simulation
    volumes:
      - ${PWD}:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges
    ports:
      - "3001:3001"
    restart: unless-stopped
    container_name: devices-simulation